### ISSUE TITLE
After i embed navigationBar & tabBar, how to dismiss transition beneath the tabBar & navBar

### ISSUE THREAD

**Issue by cliff357** [aunnnn/AppStoreiOS11InteractiveTransition#17]
First, thank you for your interaction transition demo, this is very helpful and nice. 

But there is one Issue after I embed navigation bar & tab bar 

![wriedBehaviour](https://user-images.githubusercontent.com/22883449/70770008-b237cf00-1da6-11ea-81bd-a1a85fe6a6a9.gif)

**Comment by cliff357** [comment]
solved with creating a new navbar & tabBar when you dismiss transition

**Comment by paopao517** [comment]
> solved with creating a new navbar & tabBar when you dismiss transition

What's the solution?
